language: java
dist: trusty

jdk:
  - oraclejdk8

sudo:
  - required

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS k_geo; CREATE DATABASE k_geo;' -uroot

install: true

script:
  - mvn clean compile flyway:clean flyway:migrate install

notifications:
  email:
  - herve.tchepannou@gmail.com
