language: java
dist: trusty
sudo: required

jdk: oraclejdk8


services:
  - mysql

install: true

script:
  - mvn -q install --settings settings.xml

notifications:
  email:
  - herve.tchepannou@gmail.com

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: io-tchepannou-k-geo
  on: master
