spring:
  datasource:
    url: mysql://k.cwj11t2vidmo.us-east-1.rds.amazonaws.com:3306/k_geo
    username: kadmin
    password: kadmin

flyway:
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  url: ${spring.datasource.url}

swagger:
  protocol: https
